#!/bin/bash
set -e

sudo dnf update -y
sudo dnf install git httpd -y

sudo systemctl start httpd
sudo systemctl enable httpd

TEMP_DIR=$(mktemp -d)
git clone https://github.com/vaishalichilhate04/ASG-LB-Project.git "$TEMP_DIR"

sudo cp "$TEMP_DIR/index.html" /var/www/html/
rm -rf "$TEMP_DIR"

sudo chown -R apache:apache /var/www/html
sudo chmod -R 755 /var/www/html
